/**
 * DEMO DATA - Real historical players / teams for testing.
 * Clearly marked as Demo Data. Do not treat as live stats source.
 * Sources: Public NBA historical knowledge (Basketball-Reference style facts).
 * Last Updated for this demo: 2026-09-15
 */

import type { Player, Team, Arena, Championship, Record, DataSourceMeta } from '@/types';

export const DEMO_META: DataSourceMeta = {
  source: 'Demo Data (Historical public records)',
  last_updated: '2026-09-15T00:00:00Z',
  is_demo: true,
};

export const DEMO_TEAMS: Team[] = [
  {
    id: 'team-chi',
    name: 'Chicago Bulls',
    abbreviation: 'CHI',
    city: 'Chicago',
    conference: 'East',
    division: 'Central',
    founded_year: 1966,
    arena_id: 'arena-united',
    primary_color: '#CE1141',
    secondary_color: '#000000',
    logo_url: null,
    championships: 6,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'team-lal',
    name: 'Los Angeles Lakers',
    abbreviation: 'LAL',
    city: 'Los Angeles',
    conference: 'West',
    division: 'Pacific',
    founded_year: 1947,
    arena_id: 'arena-crypto',
    primary_color: '#552583',
    secondary_color: '#FDB927',
    logo_url: null,
    championships: 17,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'team-gsw',
    name: 'Golden State Warriors',
    abbreviation: 'GSW',
    city: 'San Francisco',
    conference: 'West',
    division: 'Pacific',
    founded_year: 1946,
    arena_id: 'arena-chase',
    primary_color: '#1D428A',
    secondary_color: '#FFC72C',
    logo_url: null,
    championships: 7,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'team-bos',
    name: 'Boston Celtics',
    abbreviation: 'BOS',
    city: 'Boston',
    conference: 'East',
    division: 'Atlantic',
    founded_year: 1946,
    arena_id: 'arena-td',
    primary_color: '#007A33',
    secondary_color: '#BA9653',
    logo_url: null,
    championships: 18,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'team-mil',
    name: 'Milwaukee Bucks',
    abbreviation: 'MIL',
    city: 'Milwaukee',
    conference: 'East',
    division: 'Central',
    founded_year: 1968,
    arena_id: 'arena-fiserv',
    primary_color: '#00471B',
    secondary_color: '#EEE1C6',
    logo_url: null,
    championships: 2,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'team-den',
    name: 'Denver Nuggets',
    abbreviation: 'DEN',
    city: 'Denver',
    conference: 'West',
    division: 'Northwest',
    founded_year: 1967,
    arena_id: 'arena-ball',
    primary_color: '#0E2240',
    secondary_color: '#FEC524',
    logo_url: null,
    championships: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
];

export const DEMO_ARENAS: Arena[] = [
  {
    id: 'arena-united',
    name: 'United Center',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    capacity: 20917,
    opened_year: 1994,
    team_id: 'team-chi',
    latitude: 41.8807,
    longitude: -87.6742,
    image_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'arena-crypto',
    name: 'Crypto.com Arena',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    capacity: 19068,
    opened_year: 1999,
    team_id: 'team-lal',
    latitude: 34.0430,
    longitude: -118.2673,
    image_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'arena-chase',
    name: 'Chase Center',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    capacity: 18064,
    opened_year: 2019,
    team_id: 'team-gsw',
    latitude: 37.7680,
    longitude: -122.3877,
    image_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'arena-td',
    name: 'TD Garden',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    capacity: 19156,
    opened_year: 1995,
    team_id: 'team-bos',
    latitude: 42.3662,
    longitude: -71.0621,
    image_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'arena-fiserv',
    name: 'Fiserv Forum',
    city: 'Milwaukee',
    state: 'WI',
    country: 'USA',
    capacity: 17500,
    opened_year: 2018,
    team_id: 'team-mil',
    latitude: 43.0451,
    longitude: -87.9172,
    image_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'arena-ball',
    name: 'Ball Arena',
    city: 'Denver',
    state: 'CO',
    country: 'USA',
    capacity: 19520,
    opened_year: 1999,
    team_id: 'team-den',
    latitude: 39.7487,
    longitude: -105.0077,
    image_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
];

export const DEMO_PLAYERS: Player[] = [
  {
    id: 'player-mj',
    full_name: 'Michael Jordan',
    first_name: 'Michael',
    last_name: 'Jordan',
    birth_date: '1963-02-17',
    birth_place: 'Brooklyn, New York',
    height_cm: 198,
    weight_kg: 98,
    position: 'G-F',
    jersey_number: 23,
    team_id: 'team-chi',
    draft_year: 1984,
    draft_round: 1,
    draft_pick: 3,
    college: 'North Carolina',
    is_active: false,
    is_hall_of_fame: true,
    image_url: null,
    bio: 'Demo Data: 6× NBA Champion, 5× MVP, widely regarded as the greatest basketball player of all time.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-lbj',
    full_name: 'LeBron James',
    first_name: 'LeBron',
    last_name: 'James',
    birth_date: '1984-12-30',
    birth_place: 'Akron, Ohio',
    height_cm: 206,
    weight_kg: 113,
    position: 'F',
    jersey_number: 23,
    team_id: 'team-lal',
    draft_year: 2003,
    draft_round: 1,
    draft_pick: 1,
    college: null,
    is_active: true,
    is_hall_of_fame: false,
    image_url: null,
    bio: 'Demo Data: 4× NBA Champion, 4× MVP, all-time leading scorer.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-kobe',
    full_name: 'Kobe Bryant',
    first_name: 'Kobe',
    last_name: 'Bryant',
    birth_date: '1978-08-23',
    birth_place: 'Philadelphia, Pennsylvania',
    height_cm: 198,
    weight_kg: 96,
    position: 'G',
    jersey_number: 24,
    team_id: 'team-lal',
    draft_year: 1996,
    draft_round: 1,
    draft_pick: 13,
    college: null,
    is_active: false,
    is_hall_of_fame: true,
    image_url: null,
    bio: 'Demo Data: 5× NBA Champion, 18× All-Star. Mamba Mentality.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-curry',
    full_name: 'Stephen Curry',
    first_name: 'Stephen',
    last_name: 'Curry',
    birth_date: '1988-03-14',
    birth_place: 'Akron, Ohio',
    height_cm: 188,
    weight_kg: 84,
    position: 'G',
    jersey_number: 30,
    team_id: 'team-gsw',
    draft_year: 2009,
    draft_round: 1,
    draft_pick: 7,
    college: 'Davidson',
    is_active: true,
    is_hall_of_fame: false,
    image_url: null,
    bio: 'Demo Data: 4× NBA Champion, 2× MVP, revolutionized the 3-point game.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-kd',
    full_name: 'Kevin Durant',
    first_name: 'Kevin',
    last_name: 'Durant',
    birth_date: '1988-09-29',
    birth_place: 'Washington, D.C.',
    height_cm: 211,
    weight_kg: 109,
    position: 'F',
    jersey_number: 35,
    team_id: null,
    draft_year: 2007,
    draft_round: 1,
    draft_pick: 2,
    college: 'Texas',
    is_active: true,
    is_hall_of_fame: false,
    image_url: null,
    bio: 'Demo Data: 2× NBA Champion, 2× Finals MVP, elite scorer.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-shaq',
    full_name: "Shaquille O'Neal",
    first_name: 'Shaquille',
    last_name: "O'Neal",
    birth_date: '1972-03-06',
    birth_place: 'Newark, New Jersey',
    height_cm: 216,
    weight_kg: 147,
    position: 'C',
    jersey_number: 34,
    team_id: 'team-lal',
    draft_year: 1992,
    draft_round: 1,
    draft_pick: 1,
    college: 'LSU',
    is_active: false,
    is_hall_of_fame: true,
    image_url: null,
    bio: 'Demo Data: 4× NBA Champion, 3× Finals MVP, dominant center.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-magic',
    full_name: 'Magic Johnson',
    first_name: 'Earvin',
    last_name: 'Johnson',
    birth_date: '1959-08-14',
    birth_place: 'Lansing, Michigan',
    height_cm: 206,
    weight_kg: 100,
    position: 'G',
    jersey_number: 32,
    team_id: 'team-lal',
    draft_year: 1979,
    draft_round: 1,
    draft_pick: 1,
    college: 'Michigan State',
    is_active: false,
    is_hall_of_fame: true,
    image_url: null,
    bio: 'Demo Data: 5× NBA Champion, 3× MVP, legendary point guard.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-bird',
    full_name: 'Larry Bird',
    first_name: 'Larry',
    last_name: 'Bird',
    birth_date: '1956-12-07',
    birth_place: 'West Baden Springs, Indiana',
    height_cm: 206,
    weight_kg: 100,
    position: 'F',
    jersey_number: 33,
    team_id: 'team-bos',
    draft_year: 1978,
    draft_round: 1,
    draft_pick: 6,
    college: 'Indiana State',
    is_active: false,
    is_hall_of_fame: true,
    image_url: null,
    bio: 'Demo Data: 3× NBA Champion, 3× MVP, Celtics legend.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-kareem',
    full_name: 'Kareem Abdul-Jabbar',
    first_name: 'Kareem',
    last_name: 'Abdul-Jabbar',
    birth_date: '1947-04-16',
    birth_place: 'New York City, New York',
    height_cm: 218,
    weight_kg: 102,
    position: 'C',
    jersey_number: 33,
    team_id: 'team-lal',
    draft_year: 1969,
    draft_round: 1,
    draft_pick: 1,
    college: 'UCLA',
    is_active: false,
    is_hall_of_fame: true,
    image_url: null,
    bio: 'Demo Data: 6× NBA Champion, all-time leading scorer until 2023, skyhook.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-russell',
    full_name: 'Bill Russell',
    first_name: 'Bill',
    last_name: 'Russell',
    birth_date: '1934-02-12',
    birth_place: 'Monroe, Louisiana',
    height_cm: 208,
    weight_kg: 98,
    position: 'C',
    jersey_number: 6,
    team_id: 'team-bos',
    draft_year: 1956,
    draft_round: 1,
    draft_pick: 2,
    college: 'San Francisco',
    is_active: false,
    is_hall_of_fame: true,
    image_url: null,
    bio: 'Demo Data: 11× NBA Champion, greatest winner in team sports history.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-duncan',
    full_name: 'Tim Duncan',
    first_name: 'Tim',
    last_name: 'Duncan',
    birth_date: '1976-04-25',
    birth_place: 'Christiansted, U.S. Virgin Islands',
    height_cm: 211,
    weight_kg: 113,
    position: 'F-C',
    jersey_number: 21,
    team_id: null,
    draft_year: 1997,
    draft_round: 1,
    draft_pick: 1,
    college: 'Wake Forest',
    is_active: false,
    is_hall_of_fame: true,
    image_url: null,
    bio: 'Demo Data: 5× NBA Champion, 2× MVP, Spurs cornerstone.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-giannis',
    full_name: 'Giannis Antetokounmpo',
    first_name: 'Giannis',
    last_name: 'Antetokounmpo',
    birth_date: '1994-12-06',
    birth_place: 'Athens, Greece',
    height_cm: 211,
    weight_kg: 110,
    position: 'F',
    jersey_number: 34,
    team_id: 'team-mil',
    draft_year: 2013,
    draft_round: 1,
    draft_pick: 15,
    college: null,
    is_active: true,
    is_hall_of_fame: false,
    image_url: null,
    bio: 'Demo Data: 1× NBA Champion, 2× MVP, Greek Freak.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-jokic',
    full_name: 'Nikola Jokić',
    first_name: 'Nikola',
    last_name: 'Jokić',
    birth_date: '1995-02-19',
    birth_place: 'Sombor, Serbia',
    height_cm: 211,
    weight_kg: 129,
    position: 'C',
    jersey_number: 15,
    team_id: 'team-den',
    draft_year: 2014,
    draft_round: 2,
    draft_pick: 41,
    college: null,
    is_active: true,
    is_hall_of_fame: false,
    image_url: null,
    bio: 'Demo Data: 1× NBA Champion, 3× MVP, elite playmaking center.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-ai',
    full_name: 'Allen Iverson',
    first_name: 'Allen',
    last_name: 'Iverson',
    birth_date: '1975-06-07',
    birth_place: 'Hampton, Virginia',
    height_cm: 183,
    weight_kg: 75,
    position: 'G',
    jersey_number: 3,
    team_id: null,
    draft_year: 1996,
    draft_round: 1,
    draft_pick: 1,
    college: 'Georgetown',
    is_active: false,
    is_hall_of_fame: true,
    image_url: null,
    bio: 'Demo Data: 1× MVP, cultural icon, fearless scorer.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'player-wilt',
    full_name: 'Wilt Chamberlain',
    first_name: 'Wilt',
    last_name: 'Chamberlain',
    birth_date: '1936-08-21',
    birth_place: 'Philadelphia, Pennsylvania',
    height_cm: 216,
    weight_kg: 125,
    position: 'C',
    jersey_number: 13,
    team_id: null,
    draft_year: 1959,
    draft_round: 1,
    draft_pick: 3, // territorial
    college: 'Kansas',
    is_active: false,
    is_hall_of_fame: true,
    image_url: null,
    bio: 'Demo Data: 2× NBA Champion, 100-point game, statistical monster.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
];

export const DEMO_CHAMPIONSHIPS: Championship[] = [
  {
    id: 'champ-1996',
    year: 1996,
    season: '1995-96',
    team_id: 'team-chi',
    opponent_team_id: null,
    series_result: '4-2',
    mvp_player_id: 'player-mj',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'champ-2000',
    year: 2000,
    season: '1999-00',
    team_id: 'team-lal',
    opponent_team_id: null,
    series_result: '4-2',
    mvp_player_id: 'player-shaq',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'champ-2015',
    year: 2015,
    season: '2014-15',
    team_id: 'team-gsw',
    opponent_team_id: null,
    series_result: '4-2',
    mvp_player_id: 'player-curry',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'champ-2021',
    year: 2021,
    season: '2020-21',
    team_id: 'team-mil',
    opponent_team_id: null,
    series_result: '4-2',
    mvp_player_id: 'player-giannis',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'champ-2023',
    year: 2023,
    season: '2022-23',
    team_id: 'team-den',
    opponent_team_id: null,
    series_result: '4-1',
    mvp_player_id: 'player-jokic',
    created_at: '2024-01-01T00:00:00Z',
  },
];

export const DEMO_RECORDS: Record[] = [
  {
    id: 'rec-100pts',
    category: 'points_game',
    player_id: 'player-wilt',
    team_id: null,
    value: 100,
    season: '1961-62',
    game_id: null,
    description: 'Most points in a single game (Demo Data)',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'rec-career-pts',
    category: 'points_career',
    player_id: 'player-lbj',
    team_id: null,
    value: 40000, // approximate historical milestone note - Demo
    season: null,
    game_id: null,
    description: 'All-time leading scorer (Demo Data - verify live source)',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
];
